name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull freimanuribe15/cicd-pipeline:latest
    - name: Delete Old docker container
      run: sudo docker rm -f freimanuribe15/cicd-pipeline || true
    - name: Run Docker Container
      run: sudo docker run -d -p 3000:8080 --name cicd-pipeline-container freimanuribe15/cicd-pipeline
