name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Check Docker version
        run: docker --version

      - name: Pull Docker image
        run: docker pull freimanuribe15/cicd-pipeline:latest

      - name: List Docker containers
        run: docker ps -a

      - name: Delete Old docker container
        run: docker rm -f cicd-pipeline-container || true

      - name: Run Docker Container
        run: docker run -d -p 3000:8080 --name cicd-pipeline-container freimanuribe15/cicd-pipeline

      - name: List running Docker containers
        run: docker ps
